# Generated by Django 3.2 on 2021-04-21 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('modality', models.IntegerField(choices=[(1, 'Fixed Income'), (2, 'Variable Income'), (3, 'Cripto')])),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ip', models.CharField(max_length=12)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('operation', models.IntegerField(choices=[(1, 'Apply'), (2, 'Rescue')])),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.assets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
