# Generated by Django 3.2 on 2021-04-21 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationredemption',
            name='assets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_redemption_assets', to='investment.assets'),
        ),
        migrations.AlterField(
            model_name='applicationredemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_redemption_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
